--
--
PRAGMA foreign_keys=OFF;
PRAGMA journal_mode=WAL;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS BTSDB (
   `id` INTEGER PRIMARY KEY NOT NULL,
   `timestamp` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
   `GSM.Identity.BSIC.BCC` VARCHAR(80) NOT NULL DEFAULT '',
   `GSM.Identity.BSIC.NCC` VARCHAR(80) NOT NULL DEFAULT '',
   `GSM.Identity.CI` VARCHAR(80) NOT NULL DEFAULT '',
   `GSM.Identity.LAC` VARCHAR(80) NOT NULL DEFAULT '',
   `GSM.Identity.MCC` VARCHAR(3) NOT NULL DEFAULT '',
   `GSM.Identity.MNC` VARCHAR(2) NOT NULL DEFAULT '',
   `GSM.Identity.ShortName` VARCHAR(200) NOT NULL DEFAULT '',
   `GSM.Radio.C0` VARCHAR(5) NOT NULL DEFAULT '',
   `GSM.Radio.Band` VARCHAR(5) NOT NULL DEFAULT '',
   `GSM.Radio.NeighbourARFCNs` TEXT NOT NULL DEFAULT ''
);
COMMIT;
